### ISSUE TITLE
v0.3.7 not scrolling on many pages. 

### ISSUE THREAD

**Issue by chris-hdez** [iaarchiver/MinimalScrollbar#10] opened 2017-09-05 06:49 UTC
Chrome version 61.0.3163.71 (Beta)
Same result on stable release if I remember correctly.

Bar will not move when using the wheel. 
If the bar doesn't move when using the wheel, you can't drag the bar with mouse pointer either. 

Examples that will not scroll.  
https://www.facebook.com/ 
https://www.cnn.com/*
https://guides.github.com/activities/hello-world/
https://github.com/explore
https://github.com/iaarchiver/MinimalScrollbar/issues/*

**Comment by Pesoen** [comment] 2017-09-08 15:47
same issue here.

**Comment by iaarchiver** [comment] 2017-11-20 08:02
duplicate of #12 
fixed this in v0.4

**Closed by iaarchiver** 2017-11-20 08:02 UTC
